# Generated by Django 3.1.7 on 2021-04-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
